[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "runtime"
    version = "@project.version@"
    path = "../runtime-api-native/build/libs/runtime-api-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["runtime"]
